<h1>Willkommen im elektronischen Qualitätsmanagementsystem der Uni Hildesheim</h1>

<p>
Das elektronische QM-System der Universität zeigt die Prozesse und Abläufe der 
Universität Hildesheim und bietet Zugriff auf wichtige Dokumente zu einzelnen Prozessen. 
Die <a href="process">Prozesslandschaft</a> zeigt die Abläufe in Forschung, Lehre und Administration in 
einer grafischen Darstellung auf unterschiedlichen Detaillierungsebenen. 
Eine Navigation durch die Prozesslandschaft ist jeweils durch Anklicken der Prozesse 
möglich.
</p>

<p>
Derzeit wird auch daran gearbeitet, das Verkündungsblatt der Universität Hildesheim 
elektronisch verfügbar zu machen. Die verfügbaren Ordnungen werden durch das 
Justiziariat rückwärts-chronologisch ergänzt, so dass sich neuere Ordnungen bereits 
im System finden lassen.
</p>

<p>
Diese Seite befindet sich momentan noch im Aufbau. Bisher sind nur eingeschränkte 
Funktionalitäten verfügbar. An der Erweiterung und Verbesserung wird gearbeitet. 
Für eventuelle Störungen im Probebetrieb wird um Verständnis gebeten. 
Hinweise, Anregungen und Fehlermeldungen bitte per E-Mail an 
<a href="mailto:ditzel@uni-hildesheim.de">ditzel@uni-hildesheim.de</a>.
</p>